language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

script: ./gradlew test

after_script: cat rxbus/build/test-results/test/*.xml

