language: java
jdk: oraclejdk8

script: ./gradlew check

after_script: cat build/test-results/test/*.xml

notifications:
  email: false
  slack:
    rooms:
      secure: fnYHFSJO8m/OLjzf9+KGiXGYk6SL98rYzoHBfdMjQD0G4P9Bj+9hWyXLAK1RQ03zgaCUtWZ/k18uDImyWoXfqcsSYEHqRK+GN1XIGaxRolMiHmkosxzGJ4ywBQCYKWajIW4/OM3Ijl2LlUhD92L4C3DjMSyU7bQF6vkqrESzvswHz16DIzP8JwCPLwFCXCC2kBnjWcLbs/A2BEr54x5jkVrrqx13s5y6rkshOFM7j8KDvLIF792kfckNlTKrtndPIPIGn9yjA74Ck9svt2Y8eOUKdrOy407yKlkcQWkXUWuP4iO3MTrEDOVxX4mwTiLtWG7++LXAZMoMRhtV/1Jmxqd3soqkCgzPYcqVl6b23a0CPhOMFv02GFDN+csNO1cwYXd2+WozDffo7aV0FOIBcJGcP9XSzlbjp58mDLt5wSCBb57iYgBUV+ykrC1Ywca3d8c5e4v/QuXiUeI/F73HnY1gA0hTTjJAMSLstrxmiLCOgQHCQDi0kswphixBi+8I9uM8lYQeFFmlXsTAUREA0MICZGsEtd671s9TIDGbPOU23/xKweHhaTfu7XIgfL+gC7hMvJP0HYDqIFPZ1pJCSp7JpLrJfg7N+7B31qBoOIq4MutigQscyedd71lDZ4yIVmKrZnUJ7qRDzbjweHr0hMN+WkhQ557PVJgycoDnbnI=
    on_success: change
