language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27

script: ./gradlew test

after_script: cat rxbus/build/test-results/test/*.xml
